defaults: 
  - base_config
  - _self_
  - dataset: full 
  - tokenizer: space_tokenizer
  - model: gpt2_lm

dataset: 
  name: 'transformersegmentation/CHILDES_EnglishNA'

experiment: 
  seed: 42 
  dry_run: True
  group: Test
  name: Test

data_preprocessing:
  max_input_length: 128

trainer: 
  batch_size: 128 # across 8 GPUs gives an effective batch size of 1024
  lr: 1e-4 # 1e-4 is used in fairseq; 1e-3 is default in huggingface
  num_warmup_steps: 14_000
  max_training_steps: 100_000