DATASET:
  desc: Dataset parameters
  value:
    root_path: data/Eng-NA/prepared
EXPERIMENT:
  desc: Experiment details
  value:
    name: experiment_eng-na
    seed: 32
LOGGING:
  desc: Logging parameters
  value:
    log_interval: 200
    save_best_model: True
    save_checkpoints: True
    save_final_model: True
MODEL:
  desc: Model parameters
  value:
    dropout: 0.05
    hidden_size: 64
    inner_linear: 2048
    n_layers: 12
    tied: False
TRAINING:
  desc: Training parameters
  value:
    batch_size: 128
    clip: 0.25
    epochs: 200
    lr: 0.003
    momentum: 0.99
    sequence_length: 64