method: bayes
metric:
  goal: minimize
  name: valid.loss
parameters:
  dropout:
    distribution: categorical
    values: [0.05, 0.1, 0.2, 0.3]
  hidden_size:
    distribution: categorical
    values: [64, 128, 256, 512]
  inner_linear:
    distribution: categorical
    values: [512, 1024, 2048]
  n_layers:
    distribution: categorical
    values: [8, 10, 12, 14]
  epochs:
    distribution: categorical
    values: [300]
  lr:
    distribution: categorical
    values: [0.003, 0.001, 0.03, 0.01, 0.3, 0.1]
  momentum:
    distribution: categorical
    values: [0.99, 0.9, 0]

program: run_model.py
command:
  - ${env}
  - python
  - ${program}
  - configs/basic.yaml
  - "--resubmit_after"
  - 0.03
  - ${args}
